### ISSUE TITLE
index page forced to have post

### ISSUE THREAD

**Issue by TravisTheTechie** [testdouble/grunt-markdown-blog#24]
So we have something pretty simple...

```
<title><%= post && typeof post.title == 'function' ? post.title() : site.name %></title>
```

Which generally works great. Pages that are blog posts have the right title, other pages have the generic name. The index page though has the lastest post stored in post and nothing unique to say it's in the index I can find.

**Comment by davemo** [comment]
I took a look at incorporating this as part of v1.3.0 but I think migrating `index` to be a `page` itself breaks a number of assumptions in the existing code that make it non-trivial. 😢 

I suspect not many people are still using this plugin and it's been a while so I'm going to close this for now.
