### ISSUE TITLE
page template currently expects the page to be in the 'post' property

### ISSUE THREAD

**Issue by jasonkarns** [testdouble/grunt-markdown-blog#7]
It strikes me as odd that within a page template, it expects the page object to be `post`. I imagine this is just a compromise since state pages were added after the fact?

**Comment by davemo** [comment]
> I vote just to make a property called page that refers to the same object
that post does.

[Done!](https://github.com/testdouble/grunt-markdown-blog/pull/28/commits/d511b042b19f6251a9eff9617b3938e514b93887) 🤓
