### ISSUE TITLE
Remove the build-time assets from the generated assets

### ISSUE THREAD

**Issue by jasonkarns** [testdouble/grunt-markdown-blog#8]
As a static site generator, it doesn't make sense to have all the build-time assets as part of the site payload. For instance, the underscore templates and underscore itself are dead weight that are sent down with the static HTML files. These assets are only needed during build time, but due to their presence in `app/`, they are part of the built assets, too.

**Comment by davemo** [comment]
I think is fixed implicitly, but I also found that I just customized `config/application.{coffee,js` to include the following:

```coffeescript
module.exports = (lineman) ->

  removeTasks:
    common: lineman.config.application.removeTasks.common.concat("coffee", "pug:templates", "handlebars", "jst", "jshint")
```

This lightens the runtime speed for `build` and `run` but also ensures my final `{dist/generated}/js/app.js` doesn't include anything else.
